---
title: 'DATA607 - Final Project'
subtitle: 'Cycling Data'
author: "Donald Butler"
date: "12/04/2021"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction


## Load required R Libraries

```{r library, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)

# Federal holidays obtained from https://www.opm.gov/policy-data-oversight/pay-leave/federal-holidays
holidays <- as.Date(c('2018-01-01', '2018-01-15', '2018-02-19', '2018-05-28', '2018-07-04',
                      '2018-09-03', '2018-10-08', '2018-11-12', '2018-11-22', '2018-12-25',
                      '2019-01-01', '2019-01-21', '2019-02-18', '2019-05-27', '2019-07-04',
                      '2019-09-02', '2019-10-14', '2019-11-11', '2019-11-28', '2019-12-25'))

get_season <- function(date) {
  # 1 (Winter), 2 (Spring), 3 (Summer), 4 (Fall)
  return (((lubridate::month(date + 10) - 1) %/% 3) + 1)
}

is.holiday <- function(date) {
  return (ifelse(date %in% holidays, 1, 0))
}

```

## Download Bike Share Data

```{r download_zips, warning=FALSE, message=FALSE}
for (year in 2018:2019) {
  for (month in 1:12) {
    zipfile <- paste0(year, str_pad(month, 2, "left", "0"), "-capitalbikeshare-tripdata.zip")
    if (!file.exists(paste0('./DATA/ZIPS/', zipfile))) {
      download.file(paste0('https://s3.amazonaws.com/capitalbikeshare-data/', zipfile), paste0('./DATA/ZIPS/',zipfile))
      unzip(paste0('./DATA/ZIPS/',zipfile), exdir = 'DATA')
    }
  }
}
```

## Read extracted .csv files

```{r read_csv}
filenames <- list.files(path = './DATA/', pattern = '.csv')

df <- tibble()

for (i in 1:length(filenames)) {
  tmp <- read_csv(paste0('./DATA/', filenames[i]), show_col_types = FALSE) %>%
    rename(start_date = `Start date`, member_type = `Member type`) %>%
    mutate(dteday = as.Date(start_date)) %>%
    group_by(dteday) %>%
    count(member_type, name = 'cnt') %>%
    mutate(yr = as.integer(lubridate::year(dteday)),
           mnth = as.integer(lubridate::month(dteday)),
           season = as.integer(get_season(dteday)),
           holiday = as.integer(is.holiday(dteday)),
           weekday = as.integer(lubridate::wday(dteday) - 1),
           workingday = as.integer(ifelse(holiday == 0 & weekday %in% c(1:5), 1, 0)),
           member = as.integer(ifelse(member_type == 'Member', 1, 0))) %>%
    select(dteday,
           season,
           yr,
           mnth,
           holiday,
           weekday,
           workingday,
           member,
           cnt)

  df <- df %>% rbind(tmp)
}

df

```

